# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-23 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlike',
            name='post_type',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
