# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-23 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_userlike_post_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlike',
            old_name='post_type',
            new_name='like_type',
        ),
    ]
