# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-25 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180623_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='image',
        ),
    ]
